version: '3.9'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
    volumes:
      - .:/app
    env_file:
      - .env


